### ISSUE TITLE
Logo URL

### ISSUE THREAD

**Issue by theryankelly** [codeisland/healthy-homes#11]
@jwortzel Are we ok with ghhi $wgLogo pointing to http://wikihousing.org/mediawiki/index.php/WikiHousing.org instead of http://wikihousing.org/?

**Comment by goldenmeanie** [comment]
I agree it should be pointing at `/` as should the "Home" sidebar link

**Comment by jwortzel** [comment]
Hey guys! In my opinion, it's nice to have the wiki homepage and I'm not too sure how one would access it if not by the sidebar or logo. What do you guys think if we keep the "home" on the side bar and the "home" feature on the splash page directing to http://wikihousing.org/mediawiki/index.php/WikiHousing.org. But switch the ghhi $wgLogo to point to http://wikihousing.org/? 

This might allow both to be accessible. What do you guys think?

**Comment by goldenmeanie** [comment]
What is the benefit of having both? There are a couple links in the sidebar
that aren't in the replacement, but that could be addressed.

**Comment by jwortzel** [comment]
I was just trying to model it after https://www.wikipedia.org where they use the splash page for general usage (and most of the traffic), but the wikihome page to communicate with the users a bit more (i.e. weekly updates, events etc.) Maybe "Home" is the wrong name for it, again I was just trying to model it after wikipedia.

**Comment by goldenmeanie** [comment]
Oh. The main categories (Housing Hazards et al) aren't part of the sidebar?

It seems like there are some information architecture issues to work through. : )

**Comment by goldenmeanie** [comment]
But in general yes, it sounds like you need a new name for one of the two pages currently considered "home".

**Comment by jwortzel** [comment]
I see what you mean, the concept behind excluding (housing hazards et al) from the side bar was mainly because it seemed too cumbersome on there and I was advised to consolidate (see "compendium" on the side bar). But I definitely understand your point. In planning out the site, we found this to be the best solution.

In that light, I think let's keep the wiki "home" as it is for the moment as that is the tab we decided for the splash page.  So in sum: Splash page and side bar "home" direct to http://wikihousing.org/mediawiki/index.php/WikiHousing.org

And the ghhi $wgLogo can be directed to http://wikihousing.org/. I will create a new link on the side bar that will also direct folks to http://wikihousing.org/. 

Hope this makes sense! Again thank you so much for your help with this.

**Comment by jwortzel** [comment]
@theryankelly and @goldenmeanie  thank you both and to all Code Island members! The Website looks amazing and many people from GHHI and RIAHH are so excited! Thank you for making this possible! 

Everything operates perfectly except for the "home" button on the splash page. I know we were discussing the possible options for this link, but after discussing it with the folks at RIAHH, I think it should direct to http://wikihousing.org/mediawiki/index.php/WikiHousing.org Does this sound OK to you guys? 

Thanks again -- Jeremy

**Comment by goldenmeanie** [comment]
Home link updated as per your request.

**Comment by jwortzel** [comment]
Thank you so much!
