### ISSUE TITLE
Home Page Mock Up

### ISSUE THREAD

**Issue by theryankelly** [codeisland/healthy-homes#4]
Create mock up of new design ideas

**Comment by jwortzel** [comment]
Hello All,

I have tried to develop a mock up of what I think might be a possibility for the wikihousing.org splash page.

To summarize the intention of this "splash page," we wanted to create a less intimidating landing page and better user interface for our mediawiki site. To do this, we wanted to simulate what wikipedia has done with their site (https://www.wikipedia.org), to create a "splash page" of sorts that enables the viewer to directly search the wiki or provide a simpler user interface to guide them through the database without having to pour over initial text. Another example of such a "splash page," and one that acted as a model for me, is that of www.data.gov. 

The bellow images are what I have in mind. I wanted to include two options to search the database. First,  I thought it was good to include the easily recognizable search bar. Secondly, I thought it might be helpful to include the bottom 4 icons (all taken from the noun project). These icons will direct the viewer to those respective pages on the wiki, allowing them to explore the sections that most interests them or perhaps provide an easy outline of the resources the database offers. 

I also wanted to highlight the GHHI colors and logo and include a few tabs on the top right of the page directing folks to pages about the student organization and how to get involved. Additionally, as this wiki site will eventually be connected to the RIAHH (Rhode Island Alliance for Healthy Homes) website, I wanted to provide a means for the viewer to direct themselves back to that homepage. This RIAHH site has not yet been created but a URL will eventually need to be added.

I have two options regarding the background color as I'm not sure if the stock photo (picture 1) is feasible.

This is just a first stab, so I'd love to hear your thoughts and suggestions.  

I hope everyone has had a wonderful holiday break and a happy new year!
Thank you so much for your help with this,
Best,
Jeremy 

![wikihousing splash page 1](https://cloud.githubusercontent.com/assets/7027718/5624724/7da1a9d2-9539-11e4-9289-dee120524c1a.png)

![wikihousing spash page 2](https://cloud.githubusercontent.com/assets/7027718/5624726/80a234bc-9539-11e4-8e3f-178cad80af1c.png)

**Comment by juanitogan** [comment]
My critical opinion says that it looks great.  I think you've got the right focus in the right places given the requirements we know thus far.  Nice touch with the house in the search icon.  The first background is far better -- I think the peach background clashes.

I am still curious to understand more about the content that will be collected here so that we can be more sure that a wiki is the right content management system for this site (the wiki name can stay even if the CMS changes).

**Comment by jwortzel** [comment]
Thanks! 

The purpose of this website is to provide a free and open-sourced healthy housing database. This includes general health impacts of certain housing hazards, federal and state policies surrounding those hazards and federal and state resources already in place to help remediate these hazards (i.e. funding sources, housing rehabilitation programs and contractor training facilities). 

All of the data has been collected and edited by 70+ undergraduates from around the country. We wanted to use the wiki formate so as to allow for not just our research interns to easily add information to the site, but also professionals in the field to contribute to the information already provided on the wiki. The wiki formate also allows the data to be dynamic and be updated on an annual basis. 

Hopefully, civil servants and local legislators will find this data a valuable resource to become informed about healthy housing issues and about infrastructural gaps within the community thus facilitating grant writing and project development. Organizations such as the Green & Healthy Homes Initiative and the Rhode Island Alliance for Healthy Homes have already been working to analyze this data.  Additionally, community members can also utilize this website to learn about the local resources available for remediating housing hazards. 

I hope that helps explain the purpose of this website. Thanks again for your help with this.

**Comment by jwortzel** [comment]
I see what you mean. I think we hope to operate in much the same way Wikipedia operates in that while the web site is still a wiki it provides very accurate information and due to it's wiki nature, the information can be as accurate and up to date as possible through the help of the public. We actually have spent a bunch of time thinking about which user interface would be the best and thanks to a lot of advice and help from the Code Island folks we decided on media wiki and have since uploaded our entire database onto that format.

**Comment by juanitogan** [comment]
Okay, I'm getting the picture that you are well settled on the wiki platform.  If there is one thing a wiki does well, it is that it invites editing (albeit, by a very small percentage of the population).  I get that.  I just had to engage the conversation because helping people understand what they are asking for based on their needs versus their imagination is something I happen to do really well.  Sometimes, people think they want the red car when what they are describing is the blue car that they haven't seen yet.  I'm actually a huge fan of wikis and have hundreds of edits on Wikipedia (as well as owning a couple of their shirts).

But, since you are Brown -- and having spent most of my last 6 years working there -- I'll put the hard discussion to you:

I poke the conversation because the requirements that have been described thus far can be accomplished by any web content management system (as far as I understand web CMSs).  For example, I put up a 6-page website recently in a single evening (http://foodtoob.org).  I built it in WordPress -- not because I wanted to -- but because I could install WordPress on the web server with just a few clicks and then use it to load a mobile-responsive template that looked great for the content I wanted.  Part of me would have rather built the site by hand but WordPress fit the requirements for getting something up quick... and also for content editing anywhere, anyhow.  So, yeah, I got the site and initial content up in one evening, but then I tweaked the content from various locations on various computers as time permitted.  I could even add WordPress plugins for more types of content without digging into any code on a server.  So, while WordPress may not have been my favorite choice here, it was the right choice.

The point is that WikiMedia, Drupal, Joomla, WordPress, and probably all the others allow for online collaborative editing by many authors at any time (which is the only hard requirement I have heard thus far).  They all track versions and allow rolling back in case somebody trashes something.  Just as WikiMidia is not just for public wikis, WordPress is not just for blogs (as my site shows).  Many have better editors than WikiMedia... not to mention simpler or friendlier public interfaces.

https://en.wikipedia.org/wiki/Web_content_management_system#Notable_web_CMS

In another related story, I tried pushing for centralizing our internal programming documentation at Brown in a wiki but it never took off (even though we already had a wiki installed for use) partly because it is surprising how many people hate the editor.  It blows my mind but the CIS department at Brown would rather scatter internal docs between Word, Google Docs, and email archives than expect programmers to learn how to use a wiki editor.  Furthermore, Brown CIS also just consolidated at least 3 different CMSs (including a wiki) into one new one (not a wiki) for their outward-facing documentation, which, by the way, also allows instant editing (by CIS staff).

Thus, it is with this understanding of user behavior and system requirements that I wonder if a wiki is the right product for the target audience(s) and the content.  Have the use cases been worked through?  Where are they?  Have sites of representative content been mocked up?  If so, where are those mockups?  I don't mean just a few top pages.  If I were in charge of this project, I would want to see many content pages in the mockup so I could see how they fit together and how users might navigate through them.  Furthermore, what about user/editor/admin management?  That will be no small task given what I see here.  Also, what about scalability?  Only after all these things are demonstrated/considered would I choose a CMS product.  Should a project this size not have such consideration?  [I think this expectation from us for blind faith in the design process is why I feel a bit unsettled about committing time here.]

Regarding already having your database in wiki format, that would not sway me much.  I translate data all the time.  I would be less afraid of translating data between CMS products than I would be of choosing one without enough proof-of-concept testing.

On the other hand, to counter my own discussion, WikiMedia will do just fine even if it is not the best choice.  Thus, in that sense, perhaps this discussion is not that critical.  Then again, if 99% of Wikipedia edits are done by 1% of the editors (not the readers, the editors) then you may have a sustainability problem if you do not reach the critical mass of editors like Wikipedia has.  As such, I would take a hard look at all forms of crowd sourcing information and to see which innovations are most applicable to project.

Anyhow, I hope you understand that I am not trying to be overly critical here but, rather, constructive.  Making sure design choices are smart and unbiased is where I believe my most valuable contributions come from.  I don't always get it right myself when in design mode, but I like to know I tried to consider all views.

**Comment by theryankelly** [comment]
I like the mock up with the imaged background @jwortzel.  When you are ready we can move forward creating that page and placing it on this newly created splash page http://104.131.241.94/mediawiki/

**Comment by jwortzel** [comment]
Thank you so much @juanitogan! I really appreciate your thoughts on this. Unfortunately, at this time in the wiki site development process, I think we should stick to media wiki.

@theryankelly, I like the imaged background too! I'm ready to move forward with this splash page. Just let me know what the next steps might be and who I should contact.

**Comment by jwortzel** [comment]
![noun_76836](https://cloud.githubusercontent.com/assets/7027718/5995060/9f3c4b9c-aa56-11e4-8444-9ffb1f788f33.png)
![noun_4204](https://cloud.githubusercontent.com/assets/7027718/5995059/9f388ea8-aa56-11e4-8312-58c639bb5cfe.png)
![noun_2554](https://cloud.githubusercontent.com/assets/7027718/5995062/9f7a0496-aa56-11e4-822f-d09d4a40f053.png)
![noun_17038](https://cloud.githubusercontent.com/assets/7027718/5995061/9f4312e2-aa56-11e4-924b-0aef296dfb0b.png)
![noun_4215](https://cloud.githubusercontent.com/assets/7027718/5995058/9f387134-aa56-11e4-9a12-86965794a9fc.png)
![noun_76836](https://cloud.githubusercontent.com/assets/7027718/5995065/b2294bba-aa56-11e4-8893-f23960eeeb7f.png)
![noun_4204](https://cloud.githubusercontent.com/assets/7027718/5995067/b239ce40-aa56-11e4-98b2-aa6fab151bcb.png)
![noun_2554](https://cloud.githubusercontent.com/assets/7027718/5995069/b2740f38-aa56-11e4-87fd-ca063f435b40.png)
![noun_17038](https://cloud.githubusercontent.com/assets/7027718/5995068/b26951ce-aa56-11e4-99da-409f8f57b3a0.png)
![noun_4215](https://cloud.githubusercontent.com/assets/7027718/5995066/b22b192c-aa56-11e4-86ec-4c694e2e288c.png)

**Comment by theryankelly** [comment]
The splash page can be viewed here: http://104.131.241.94/healthy-homes/

There are currently three outstanding issues before we switch over to wikihousing.org
#6  #7 #8
